/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  LocationSegments,
  MatchResults,
  RouterHistory,
} from '@stencil/router';
import {
  Enseignant,
} from './global/enseignant';
import {
  Formation,
} from './global/formation';
import {
  Promotion,
} from './global/promotion';
import {
  utilisateurs,
} from './global/utilisateurs';
import {
  Etudiant,
} from './global/etudiant';


export namespace Components {

  interface AdmHeader {
    'history': RouterHistory;
  }
  interface AdmHeaderAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface AdmHome {}
  interface AdmHomeAttributes extends StencilHTMLAttributes {}

  interface AdmRoot {}
  interface AdmRootAttributes extends StencilHTMLAttributes {}

  interface EnsAdd {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface EnsAddAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface EnsCard {
    'enseignant': Enseignant;
  }
  interface EnsCardAttributes extends StencilHTMLAttributes {
    'enseignant'?: Enseignant;
    'onEnseignantSupprime'?: (event: CustomEvent) => void;
  }

  interface EnsDetail {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface EnsDetailAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface EnsForm {
    'enseignant': Enseignant;
    'history': RouterHistory;
    'isEditMode': boolean;
    'match': MatchResults;
  }
  interface EnsFormAttributes extends StencilHTMLAttributes {
    'enseignant'?: Enseignant;
    'history'?: RouterHistory;
    'isEditMode'?: boolean;
    'match'?: MatchResults;
  }

  interface EnsHome {}
  interface EnsHomeAttributes extends StencilHTMLAttributes {}

  interface EnsSearch {}
  interface EnsSearchAttributes extends StencilHTMLAttributes {}

  interface FormAdd {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface FormAddAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface FormDetail {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface FormDetailAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface FormForm {
    'formation': Formation;
    'history': RouterHistory;
    'isEditMode': boolean;
    'match': MatchResults;
  }
  interface FormFormAttributes extends StencilHTMLAttributes {
    'formation'?: Formation;
    'history'?: RouterHistory;
    'isEditMode'?: boolean;
    'match'?: MatchResults;
  }

  interface FormHome {
    'history': RouterHistory;
  }
  interface FormHomeAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface FormSearch {
    'history': RouterHistory;
  }
  interface FormSearchAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface PromoAdd {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface PromoAddAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface PromoDetail {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface PromoDetailAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface PromoForm {
    'history': RouterHistory;
    'isEditMode': boolean;
    'match': MatchResults;
    'promotion': Promotion;
  }
  interface PromoFormAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'isEditMode'?: boolean;
    'match'?: MatchResults;
    'promotion'?: Promotion;
  }

  interface PromoHome {
    'history': RouterHistory;
  }
  interface PromoHomeAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface PromoSearch {
    'history': RouterHistory;
  }
  interface PromoSearchAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface PromoTable {
    'history': RouterHistory;
    'promotions': Promotion[];
  }
  interface PromoTableAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'onPromotionSupprime'?: (event: CustomEvent) => void;
    'promotions'?: Promotion[];
  }

  interface AuthentificationAuthen {
    'filtrer': () => void;
    'history': RouterHistory;
    'utilisateur': utilisateurs;
  }
  interface AuthentificationAuthenAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'utilisateur'?: utilisateurs;
  }

  interface AddEtudForm {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AddEtudFormAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface EvaeEtudiantAdd {
    'Data': any;
    'etudiant': any;
    'history': RouterHistory;
  }
  interface EvaeEtudiantAddAttributes extends StencilHTMLAttributes {
    'Data'?: any;
    'etudiant'?: any;
    'history'?: RouterHistory;
  }

  interface EvaeEtudiants {
    'etudiants': Etudiant[];
    'formation': any;
    'history': RouterHistory;
    'retour': () => void;
  }
  interface EvaeEtudiantsAttributes extends StencilHTMLAttributes {
    'etudiants'?: Etudiant[];
    'formation'?: any;
    'history'?: RouterHistory;
  }

  interface EvaeFormEtudiants {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface EvaeFormEtudiantsAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface EvaluationList {}
  interface EvaluationListAttributes extends StencilHTMLAttributes {}

  interface EvaeFormations {
    'componentDidLoad': () => void;
    'history': RouterHistory;
  }
  interface EvaeFormationsAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface EvaeFormPromos {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface EvaeFormPromosAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface EvaePromtions {
    'formation': Formation;
    'history': RouterHistory;
    'promotions': Promotion[];
    'retour': () => void;
  }
  interface EvaePromtionsAttributes extends StencilHTMLAttributes {
    'formation'?: Formation;
    'history'?: RouterHistory;
    'promotions'?: Promotion[];
  }

  interface EvaeQualificatif {}
  interface EvaeQualificatifAttributes extends StencilHTMLAttributes {}

  interface EvaeQuestion {}
  interface EvaeQuestionAttributes extends StencilHTMLAttributes {}

  interface PageNotFound {}
  interface PageNotFoundAttributes extends StencilHTMLAttributes {}

  interface SpiEnseignant {}
  interface SpiEnseignantAttributes extends StencilHTMLAttributes {}

  interface SpiHeader {}
  interface SpiHeaderAttributes extends StencilHTMLAttributes {}

  interface SpiHome {}
  interface SpiHomeAttributes extends StencilHTMLAttributes {}

  interface SpiRoot {}
  interface SpiRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AdmHeader': Components.AdmHeader;
    'AdmHome': Components.AdmHome;
    'AdmRoot': Components.AdmRoot;
    'EnsAdd': Components.EnsAdd;
    'EnsCard': Components.EnsCard;
    'EnsDetail': Components.EnsDetail;
    'EnsForm': Components.EnsForm;
    'EnsHome': Components.EnsHome;
    'EnsSearch': Components.EnsSearch;
    'FormAdd': Components.FormAdd;
    'FormDetail': Components.FormDetail;
    'FormForm': Components.FormForm;
    'FormHome': Components.FormHome;
    'FormSearch': Components.FormSearch;
    'PromoAdd': Components.PromoAdd;
    'PromoDetail': Components.PromoDetail;
    'PromoForm': Components.PromoForm;
    'PromoHome': Components.PromoHome;
    'PromoSearch': Components.PromoSearch;
    'PromoTable': Components.PromoTable;
    'AuthentificationAuthen': Components.AuthentificationAuthen;
    'AddEtudForm': Components.AddEtudForm;
    'EvaeEtudiantAdd': Components.EvaeEtudiantAdd;
    'EvaeEtudiants': Components.EvaeEtudiants;
    'EvaeFormEtudiants': Components.EvaeFormEtudiants;
    'EvaluationList': Components.EvaluationList;
    'EvaeFormations': Components.EvaeFormations;
    'EvaeFormPromos': Components.EvaeFormPromos;
    'EvaePromtions': Components.EvaePromtions;
    'EvaeQualificatif': Components.EvaeQualificatif;
    'EvaeQuestion': Components.EvaeQuestion;
    'PageNotFound': Components.PageNotFound;
    'SpiEnseignant': Components.SpiEnseignant;
    'SpiHeader': Components.SpiHeader;
    'SpiHome': Components.SpiHome;
    'SpiRoot': Components.SpiRoot;
  }

  interface StencilIntrinsicElements {
    'adm-header': Components.AdmHeaderAttributes;
    'adm-home': Components.AdmHomeAttributes;
    'adm-root': Components.AdmRootAttributes;
    'ens-add': Components.EnsAddAttributes;
    'ens-card': Components.EnsCardAttributes;
    'ens-detail': Components.EnsDetailAttributes;
    'ens-form': Components.EnsFormAttributes;
    'ens-home': Components.EnsHomeAttributes;
    'ens-search': Components.EnsSearchAttributes;
    'form-add': Components.FormAddAttributes;
    'form-detail': Components.FormDetailAttributes;
    'form-form': Components.FormFormAttributes;
    'form-home': Components.FormHomeAttributes;
    'form-search': Components.FormSearchAttributes;
    'promo-add': Components.PromoAddAttributes;
    'promo-detail': Components.PromoDetailAttributes;
    'promo-form': Components.PromoFormAttributes;
    'promo-home': Components.PromoHomeAttributes;
    'promo-search': Components.PromoSearchAttributes;
    'promo-table': Components.PromoTableAttributes;
    'authentification-authen': Components.AuthentificationAuthenAttributes;
    'add-etud-form': Components.AddEtudFormAttributes;
    'evae-etudiant-add': Components.EvaeEtudiantAddAttributes;
    'evae-etudiants': Components.EvaeEtudiantsAttributes;
    'evae-form-etudiants': Components.EvaeFormEtudiantsAttributes;
    'evaluation-list': Components.EvaluationListAttributes;
    'evae-formations': Components.EvaeFormationsAttributes;
    'evae-form-promos': Components.EvaeFormPromosAttributes;
    'evae-promtions': Components.EvaePromtionsAttributes;
    'evae-qualificatif': Components.EvaeQualificatifAttributes;
    'evae-question': Components.EvaeQuestionAttributes;
    'page-not-found': Components.PageNotFoundAttributes;
    'spi-enseignant': Components.SpiEnseignantAttributes;
    'spi-header': Components.SpiHeaderAttributes;
    'spi-home': Components.SpiHomeAttributes;
    'spi-root': Components.SpiRootAttributes;
  }


  interface HTMLAdmHeaderElement extends Components.AdmHeader, HTMLStencilElement {}
  var HTMLAdmHeaderElement: {
    prototype: HTMLAdmHeaderElement;
    new (): HTMLAdmHeaderElement;
  };

  interface HTMLAdmHomeElement extends Components.AdmHome, HTMLStencilElement {}
  var HTMLAdmHomeElement: {
    prototype: HTMLAdmHomeElement;
    new (): HTMLAdmHomeElement;
  };

  interface HTMLAdmRootElement extends Components.AdmRoot, HTMLStencilElement {}
  var HTMLAdmRootElement: {
    prototype: HTMLAdmRootElement;
    new (): HTMLAdmRootElement;
  };

  interface HTMLEnsAddElement extends Components.EnsAdd, HTMLStencilElement {}
  var HTMLEnsAddElement: {
    prototype: HTMLEnsAddElement;
    new (): HTMLEnsAddElement;
  };

  interface HTMLEnsCardElement extends Components.EnsCard, HTMLStencilElement {}
  var HTMLEnsCardElement: {
    prototype: HTMLEnsCardElement;
    new (): HTMLEnsCardElement;
  };

  interface HTMLEnsDetailElement extends Components.EnsDetail, HTMLStencilElement {}
  var HTMLEnsDetailElement: {
    prototype: HTMLEnsDetailElement;
    new (): HTMLEnsDetailElement;
  };

  interface HTMLEnsFormElement extends Components.EnsForm, HTMLStencilElement {}
  var HTMLEnsFormElement: {
    prototype: HTMLEnsFormElement;
    new (): HTMLEnsFormElement;
  };

  interface HTMLEnsHomeElement extends Components.EnsHome, HTMLStencilElement {}
  var HTMLEnsHomeElement: {
    prototype: HTMLEnsHomeElement;
    new (): HTMLEnsHomeElement;
  };

  interface HTMLEnsSearchElement extends Components.EnsSearch, HTMLStencilElement {}
  var HTMLEnsSearchElement: {
    prototype: HTMLEnsSearchElement;
    new (): HTMLEnsSearchElement;
  };

  interface HTMLFormAddElement extends Components.FormAdd, HTMLStencilElement {}
  var HTMLFormAddElement: {
    prototype: HTMLFormAddElement;
    new (): HTMLFormAddElement;
  };

  interface HTMLFormDetailElement extends Components.FormDetail, HTMLStencilElement {}
  var HTMLFormDetailElement: {
    prototype: HTMLFormDetailElement;
    new (): HTMLFormDetailElement;
  };

  interface HTMLFormFormElement extends Components.FormForm, HTMLStencilElement {}
  var HTMLFormFormElement: {
    prototype: HTMLFormFormElement;
    new (): HTMLFormFormElement;
  };

  interface HTMLFormHomeElement extends Components.FormHome, HTMLStencilElement {}
  var HTMLFormHomeElement: {
    prototype: HTMLFormHomeElement;
    new (): HTMLFormHomeElement;
  };

  interface HTMLFormSearchElement extends Components.FormSearch, HTMLStencilElement {}
  var HTMLFormSearchElement: {
    prototype: HTMLFormSearchElement;
    new (): HTMLFormSearchElement;
  };

  interface HTMLPromoAddElement extends Components.PromoAdd, HTMLStencilElement {}
  var HTMLPromoAddElement: {
    prototype: HTMLPromoAddElement;
    new (): HTMLPromoAddElement;
  };

  interface HTMLPromoDetailElement extends Components.PromoDetail, HTMLStencilElement {}
  var HTMLPromoDetailElement: {
    prototype: HTMLPromoDetailElement;
    new (): HTMLPromoDetailElement;
  };

  interface HTMLPromoFormElement extends Components.PromoForm, HTMLStencilElement {}
  var HTMLPromoFormElement: {
    prototype: HTMLPromoFormElement;
    new (): HTMLPromoFormElement;
  };

  interface HTMLPromoHomeElement extends Components.PromoHome, HTMLStencilElement {}
  var HTMLPromoHomeElement: {
    prototype: HTMLPromoHomeElement;
    new (): HTMLPromoHomeElement;
  };

  interface HTMLPromoSearchElement extends Components.PromoSearch, HTMLStencilElement {}
  var HTMLPromoSearchElement: {
    prototype: HTMLPromoSearchElement;
    new (): HTMLPromoSearchElement;
  };

  interface HTMLPromoTableElement extends Components.PromoTable, HTMLStencilElement {}
  var HTMLPromoTableElement: {
    prototype: HTMLPromoTableElement;
    new (): HTMLPromoTableElement;
  };

  interface HTMLAuthentificationAuthenElement extends Components.AuthentificationAuthen, HTMLStencilElement {}
  var HTMLAuthentificationAuthenElement: {
    prototype: HTMLAuthentificationAuthenElement;
    new (): HTMLAuthentificationAuthenElement;
  };

  interface HTMLAddEtudFormElement extends Components.AddEtudForm, HTMLStencilElement {}
  var HTMLAddEtudFormElement: {
    prototype: HTMLAddEtudFormElement;
    new (): HTMLAddEtudFormElement;
  };

  interface HTMLEvaeEtudiantAddElement extends Components.EvaeEtudiantAdd, HTMLStencilElement {}
  var HTMLEvaeEtudiantAddElement: {
    prototype: HTMLEvaeEtudiantAddElement;
    new (): HTMLEvaeEtudiantAddElement;
  };

  interface HTMLEvaeEtudiantsElement extends Components.EvaeEtudiants, HTMLStencilElement {}
  var HTMLEvaeEtudiantsElement: {
    prototype: HTMLEvaeEtudiantsElement;
    new (): HTMLEvaeEtudiantsElement;
  };

  interface HTMLEvaeFormEtudiantsElement extends Components.EvaeFormEtudiants, HTMLStencilElement {}
  var HTMLEvaeFormEtudiantsElement: {
    prototype: HTMLEvaeFormEtudiantsElement;
    new (): HTMLEvaeFormEtudiantsElement;
  };

  interface HTMLEvaluationListElement extends Components.EvaluationList, HTMLStencilElement {}
  var HTMLEvaluationListElement: {
    prototype: HTMLEvaluationListElement;
    new (): HTMLEvaluationListElement;
  };

  interface HTMLEvaeFormationsElement extends Components.EvaeFormations, HTMLStencilElement {}
  var HTMLEvaeFormationsElement: {
    prototype: HTMLEvaeFormationsElement;
    new (): HTMLEvaeFormationsElement;
  };

  interface HTMLEvaeFormPromosElement extends Components.EvaeFormPromos, HTMLStencilElement {}
  var HTMLEvaeFormPromosElement: {
    prototype: HTMLEvaeFormPromosElement;
    new (): HTMLEvaeFormPromosElement;
  };

  interface HTMLEvaePromtionsElement extends Components.EvaePromtions, HTMLStencilElement {}
  var HTMLEvaePromtionsElement: {
    prototype: HTMLEvaePromtionsElement;
    new (): HTMLEvaePromtionsElement;
  };

  interface HTMLEvaeQualificatifElement extends Components.EvaeQualificatif, HTMLStencilElement {}
  var HTMLEvaeQualificatifElement: {
    prototype: HTMLEvaeQualificatifElement;
    new (): HTMLEvaeQualificatifElement;
  };

  interface HTMLEvaeQuestionElement extends Components.EvaeQuestion, HTMLStencilElement {}
  var HTMLEvaeQuestionElement: {
    prototype: HTMLEvaeQuestionElement;
    new (): HTMLEvaeQuestionElement;
  };

  interface HTMLPageNotFoundElement extends Components.PageNotFound, HTMLStencilElement {}
  var HTMLPageNotFoundElement: {
    prototype: HTMLPageNotFoundElement;
    new (): HTMLPageNotFoundElement;
  };

  interface HTMLSpiEnseignantElement extends Components.SpiEnseignant, HTMLStencilElement {}
  var HTMLSpiEnseignantElement: {
    prototype: HTMLSpiEnseignantElement;
    new (): HTMLSpiEnseignantElement;
  };

  interface HTMLSpiHeaderElement extends Components.SpiHeader, HTMLStencilElement {}
  var HTMLSpiHeaderElement: {
    prototype: HTMLSpiHeaderElement;
    new (): HTMLSpiHeaderElement;
  };

  interface HTMLSpiHomeElement extends Components.SpiHome, HTMLStencilElement {}
  var HTMLSpiHomeElement: {
    prototype: HTMLSpiHomeElement;
    new (): HTMLSpiHomeElement;
  };

  interface HTMLSpiRootElement extends Components.SpiRoot, HTMLStencilElement {}
  var HTMLSpiRootElement: {
    prototype: HTMLSpiRootElement;
    new (): HTMLSpiRootElement;
  };

  interface HTMLElementTagNameMap {
    'adm-header': HTMLAdmHeaderElement
    'adm-home': HTMLAdmHomeElement
    'adm-root': HTMLAdmRootElement
    'ens-add': HTMLEnsAddElement
    'ens-card': HTMLEnsCardElement
    'ens-detail': HTMLEnsDetailElement
    'ens-form': HTMLEnsFormElement
    'ens-home': HTMLEnsHomeElement
    'ens-search': HTMLEnsSearchElement
    'form-add': HTMLFormAddElement
    'form-detail': HTMLFormDetailElement
    'form-form': HTMLFormFormElement
    'form-home': HTMLFormHomeElement
    'form-search': HTMLFormSearchElement
    'promo-add': HTMLPromoAddElement
    'promo-detail': HTMLPromoDetailElement
    'promo-form': HTMLPromoFormElement
    'promo-home': HTMLPromoHomeElement
    'promo-search': HTMLPromoSearchElement
    'promo-table': HTMLPromoTableElement
    'authentification-authen': HTMLAuthentificationAuthenElement
    'add-etud-form': HTMLAddEtudFormElement
    'evae-etudiant-add': HTMLEvaeEtudiantAddElement
    'evae-etudiants': HTMLEvaeEtudiantsElement
    'evae-form-etudiants': HTMLEvaeFormEtudiantsElement
    'evaluation-list': HTMLEvaluationListElement
    'evae-formations': HTMLEvaeFormationsElement
    'evae-form-promos': HTMLEvaeFormPromosElement
    'evae-promtions': HTMLEvaePromtionsElement
    'evae-qualificatif': HTMLEvaeQualificatifElement
    'evae-question': HTMLEvaeQuestionElement
    'page-not-found': HTMLPageNotFoundElement
    'spi-enseignant': HTMLSpiEnseignantElement
    'spi-header': HTMLSpiHeaderElement
    'spi-home': HTMLSpiHomeElement
    'spi-root': HTMLSpiRootElement
  }

  interface ElementTagNameMap {
    'adm-header': HTMLAdmHeaderElement;
    'adm-home': HTMLAdmHomeElement;
    'adm-root': HTMLAdmRootElement;
    'ens-add': HTMLEnsAddElement;
    'ens-card': HTMLEnsCardElement;
    'ens-detail': HTMLEnsDetailElement;
    'ens-form': HTMLEnsFormElement;
    'ens-home': HTMLEnsHomeElement;
    'ens-search': HTMLEnsSearchElement;
    'form-add': HTMLFormAddElement;
    'form-detail': HTMLFormDetailElement;
    'form-form': HTMLFormFormElement;
    'form-home': HTMLFormHomeElement;
    'form-search': HTMLFormSearchElement;
    'promo-add': HTMLPromoAddElement;
    'promo-detail': HTMLPromoDetailElement;
    'promo-form': HTMLPromoFormElement;
    'promo-home': HTMLPromoHomeElement;
    'promo-search': HTMLPromoSearchElement;
    'promo-table': HTMLPromoTableElement;
    'authentification-authen': HTMLAuthentificationAuthenElement;
    'add-etud-form': HTMLAddEtudFormElement;
    'evae-etudiant-add': HTMLEvaeEtudiantAddElement;
    'evae-etudiants': HTMLEvaeEtudiantsElement;
    'evae-form-etudiants': HTMLEvaeFormEtudiantsElement;
    'evaluation-list': HTMLEvaluationListElement;
    'evae-formations': HTMLEvaeFormationsElement;
    'evae-form-promos': HTMLEvaeFormPromosElement;
    'evae-promtions': HTMLEvaePromtionsElement;
    'evae-qualificatif': HTMLEvaeQualificatifElement;
    'evae-question': HTMLEvaeQuestionElement;
    'page-not-found': HTMLPageNotFoundElement;
    'spi-enseignant': HTMLSpiEnseignantElement;
    'spi-header': HTMLSpiHeaderElement;
    'spi-home': HTMLSpiHomeElement;
    'spi-root': HTMLSpiRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
